// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {Test} from "forge-std/Test.sol";
import {ArcCash, IVerifier} from "../contracts/ArcCash.sol";
import {IHasher} from "../contracts/MerkleTreeWithHistory.sol";

/// Accepts every proof, so the contract's own checks can be tested in isolation. Real proofs are
/// exercised end to end in test/e2e.mjs against the true verifier.
contract YesVerifier is IVerifier {
    function verifyProof(uint256[2] calldata, uint256[2][2] calldata, uint256[2] calldata, uint256[6] calldata) external pure returns (bool) {
        return true;
    }
}

contract NoVerifier is IVerifier {
    function verifyProof(uint256[2] calldata, uint256[2][2] calldata, uint256[2] calldata, uint256[6] calldata) external pure returns (bool) {
        return false;
    }
}

contract Rejecting {
    receive() external payable {
        revert("no");
    }
}

contract ArcCashTest is Test {
    ArcCash pool;
    ArcCash strict;
    address hasher;
    uint256 constant DENOM = 10 ether;
    address alice = makeAddr("alice");
    address bob = makeAddr("bob");
    address relayer = makeAddr("relayer");

    uint256[2] pA;
    uint256[2][2] pB;
    uint256[2] pC;

    function setUp() public {
        // the real MiMC hasher bytecode generated by circomlibjs, so tree hashing is genuine
        bytes memory code = vm.parseBytes(string.concat("0x", vm.readFile("build/Hasher.bin")));
        address h;
        assembly {
            h := create(0, add(code, 0x20), mload(code))
        }
        require(h != address(0), "hasher deploy failed");
        hasher = h;
        pool = new ArcCash(new YesVerifier(), IHasher(hasher), DENOM, 20);
        strict = new ArcCash(new NoVerifier(), IHasher(hasher), DENOM, 20);
        vm.deal(alice, 1000 ether);
        vm.deal(bob, 100 ether);
    }

    function _deposit(address who, bytes32 c) internal {
        vm.prank(who);
        pool.deposit{value: DENOM}(c);
    }

    function test_deposit_updatesRootAndHistory() public {
        bytes32 r0 = pool.getLastRoot();
        _deposit(alice, bytes32(uint256(1)));
        bytes32 r1 = pool.getLastRoot();
        assertTrue(r1 != r0);
        assertTrue(pool.isKnownRoot(r0), "previous root stays valid");
        assertTrue(pool.isKnownRoot(r1));
        assertEq(pool.nextIndex(), 1);
        assertTrue(pool.commitments(bytes32(uint256(1))));
        assertEq(address(pool).balance, DENOM);
    }

    function test_deposit_rejects() public {
        _deposit(alice, bytes32(uint256(7)));
        vm.prank(bob);
        vm.expectRevert(ArcCash.CommitmentAlreadySubmitted.selector);
        pool.deposit{value: DENOM}(bytes32(uint256(7)));
        vm.prank(bob);
        vm.expectRevert(abi.encodeWithSelector(ArcCash.WrongDenomination.selector, DENOM - 1, DENOM));
        pool.deposit{value: DENOM - 1}(bytes32(uint256(8)));
    }

    function test_rootHistory_is30Deep() public {
        bytes32 first;
        for (uint256 i = 1; i <= 31; i++) {
            _deposit(alice, bytes32(i));
            if (i == 1) first = pool.getLastRoot();
        }
        assertFalse(pool.isKnownRoot(first), "root from 31 deposits ago has been forgotten");
        assertFalse(pool.isKnownRoot(bytes32(0)));
    }

    function test_withdraw_paysRecipientAndRelayer() public {
        _deposit(alice, bytes32(uint256(1)));
        bytes32 root = pool.getLastRoot();
        bytes32 nh = bytes32(uint256(99));
        pool.withdraw(pA, pB, pC, root, nh, payable(bob), payable(relayer), 0.5 ether, 0);
        assertEq(bob.balance, 100 ether + DENOM - 0.5 ether);
        assertEq(relayer.balance, 0.5 ether);
        assertTrue(pool.isSpent(nh));
        vm.expectRevert(ArcCash.NoteAlreadySpent.selector);
        pool.withdraw(pA, pB, pC, root, nh, payable(bob), payable(relayer), 0.5 ether, 0);
    }

    function test_withdraw_rejects() public {
        _deposit(alice, bytes32(uint256(1)));
        bytes32 root = pool.getLastRoot();
        vm.expectRevert(ArcCash.UnknownRoot.selector);
        pool.withdraw(pA, pB, pC, bytes32(uint256(12345)), bytes32(uint256(1)), payable(bob), payable(0), 0, 0);
        vm.expectRevert(ArcCash.FeeExceedsDenomination.selector);
        pool.withdraw(pA, pB, pC, root, bytes32(uint256(1)), payable(bob), payable(relayer), DENOM + 1, 0);
        vm.expectRevert(ArcCash.RefundNotSupported.selector);
        pool.withdraw(pA, pB, pC, root, bytes32(uint256(1)), payable(bob), payable(0), 0, 1);
        // an invalid proof is rejected by the verifier
        vm.prank(alice);
        strict.deposit{value: DENOM}(bytes32(uint256(1)));
        bytes32 strictRoot = strict.getLastRoot();
        vm.expectRevert(ArcCash.InvalidProof.selector);
        strict.withdraw(pA, pB, pC, strictRoot, bytes32(uint256(1)), payable(bob), payable(0), 0, 0);
        // a recipient that refuses the coins cannot burn the note: state is rolled back
        Rejecting rj = new Rejecting();
        vm.expectRevert(ArcCash.TransferFailed.selector);
        pool.withdraw(pA, pB, pC, root, bytes32(uint256(2)), payable(address(rj)), payable(0), 0, 0);
        assertFalse(pool.isSpent(bytes32(uint256(2))));
    }

    function test_zerosMatchGeneratedTable() public view {
        // zeros(i+1) must equal hash(zeros(i), zeros(i)) using the real hasher
        for (uint256 i = 0; i < 5; i++) {
            assertEq(pool.zeros(i + 1), pool.hashLeftRight(IHasher(hasher), pool.zeros(i), pool.zeros(i)));
        }
        assertEq(uint256(pool.zeros(0)), pool.ZERO_VALUE());
    }

    function testFuzz_depositWithdrawConserves(uint96 fee, bytes32 c) public {
        vm.assume(c != bytes32(0) && uint256(c) < pool.FIELD_SIZE() && !pool.commitments(c));
        fee = uint96(bound(fee, 0, DENOM));
        _deposit(alice, c);
        uint256 before = bob.balance + relayer.balance;
        bytes32 root = pool.getLastRoot();
        pool.withdraw(pA, pB, pC, root, keccak256(abi.encode(c)), payable(bob), payable(relayer), fee, 0);
        assertEq(bob.balance + relayer.balance - before, DENOM);
        assertEq(address(pool).balance, 0);
    }
}
